//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_EC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public CreditCard()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int ID { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string SecurityCode { get; set; }
        public string Name { get; set; }
        public Nullable<int> CreditCardType_ID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual CreditCardType CreditCardType { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
