//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_EC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesProduct
    {
        public int ID { get; set; }
        public int Product_ID { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
