//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_EC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public Manufacturer()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Address_ID { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
