//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_EC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public int ID { get; set; }
        public int Order_ID { get; set; }
        public int OrderStatus_ID { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
    }
}
