//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_EC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Note { get; set; }
        public int OrderStatus_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public int ShippingAddress_ID { get; set; }
        public int Payment_ID { get; set; }
        public Nullable<int> OrderType_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual ShippingAddress ShippingAddress { get; set; }
    }
}
