//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_EC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTypeAttribute
    {
        public ProductTypeAttribute()
        {
            this.ProductAtrributeDetails = new HashSet<ProductAtrributeDetail>();
        }
    
        public int AttributeId { get; set; }
        public string AttributeName { get; set; }
        public int ProductTypeId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<ProductAtrributeDetail> ProductAtrributeDetails { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
