//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_EC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            this.ShoppingCartDetails = new HashSet<ShoppingCartDetail>();
        }
    
        public int CartId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsAccept { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<ShoppingCartDetail> ShoppingCartDetails { get; set; }
    }
}
